# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestSupervisorcreatetopic():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_supervisorcreatetopic(self):
        self.driver.get("http://127.0.0.1:8000?test_name=supervisor_create_topics")
        time.sleep(2)
        self.driver.find_element(By.LINK_TEXT, "My Pickr↗").click()
        self.driver.find_element(By.ID, "user_name").click()
        self.driver.find_element(By.ID, "user_name").send_keys("clivia")
        self.driver.find_element(By.ID, "password").click()
        self.driver.find_element(By.ID, "password").send_keys("123456")
        self.driver.find_element(By.CSS_SELECTOR, ".submit-button").click()
        time.sleep(2)
        self.driver.find_element(By.LINK_TEXT, "+ New Topic").click()
        self.driver.find_element(By.ID, "topic_name").click()
        self.driver.find_element(By.ID, "topic_name").send_keys("test")
        self.driver.find_element(By.ID, "topic_type").click()
        dropdown = self.driver.find_element(By.ID, "topic_type")
        dropdown.find_element(By.XPATH, "//option[. = 'type0']").click()
        self.driver.find_element(By.ID, "position").send_keys("1")
        self.driver.find_element(By.ID, "description").send_keys("test")
        self.driver.find_element(By.ID, "skills").send_keys("test")
        self.driver.find_element(By.ID, "reference").send_keys("test")
        self.driver.find_element(By.CSS_SELECTOR, ".submit-button").click()
        self.driver.find_element(By.CSS_SELECTOR, ".image").click()
        self.driver.find_element(By.CSS_SELECTOR, ".link_accent > em").click()
        self.driver.find_element(By.CSS_SELECTOR, ".w-layout-vflex").click()
        self.driver.find_element(By.LINK_TEXT, "My Pickr↗").click()
        self.driver.find_element(By.XPATH, "//em[contains(.,\'Logout↗\')]").click()
