"""empty message

Revision ID: 12ad909c462d
Revises: a67f4dd8628e
Create Date: 2025-03-21 09:42:26.772616

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '12ad909c462d'
down_revision = 'a67f4dd8628e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.alter_column('comments',
               existing_type=mysql.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.alter_column('comments',
               existing_type=mysql.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
