"""empty message

Revision ID: 138395cac395
Revises: 6db26d29afd4
Create Date: 2024-11-17 13:46:46.609179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '138395cac395'
down_revision = '6db26d29afd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supervisors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expertise', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supervisors', schema=None) as batch_op:
        batch_op.drop_column('expertise')

    # ### end Alembic commands ###
