"""empty message

Revision ID: 1932fb4b29c8
Revises: 12ad909c462d
Create Date: 2025-03-21 11:28:25.518954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1932fb4b29c8'
down_revision = '12ad909c462d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_time', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('create_time')

    # ### end Alembic commands ###
