"""empty message

Revision ID: 526163470ce3
Revises: ddf7e7a01d7e
Create Date: 2025-03-09 20:12:01.642499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '526163470ce3'
down_revision = 'ddf7e7a01d7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('submit_time', sa.String(length=20), nullable=False),
    sa.Column('update_time', sa.String(length=20), nullable=False),
    sa.Column('current_plan', sa.Text(), nullable=True),
    sa.Column('next_plan', sa.Text(), nullable=True),
    sa.Column('issues', sa.Text(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reports')
    # ### end Alembic commands ###
