"""empty message

Revision ID: 60332c551c61
Revises: 68f75432a8c1
Create Date: 2024-11-17 08:50:39.160325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60332c551c61'
down_revision = '68f75432a8c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topic_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('topic_types')
    # ### end Alembic commands ###
