"""empty message

Revision ID: 68f75432a8c1
Revises: 6c9305b27ab2
Create Date: 2024-11-17 08:45:06.989192

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '68f75432a8c1'
down_revision = '6c9305b27ab2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.drop_constraint('topics_ibfk_2', type_='foreignkey')
        batch_op.drop_column('type_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('topics_ibfk_2', 'types', ['type_id'], ['id'])

    # ### end Alembic commands ###
