"""empty message

Revision ID: 6db26d29afd4
Revises: 60332c551c61
Create Date: 2024-11-17 13:33:32.302073

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6db26d29afd4'
down_revision = '60332c551c61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('topic_types')
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'types', ['type_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('type_id')

    op.create_table('topic_types',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('topic_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name='topic_types_ibfk_1'),
    sa.ForeignKeyConstraint(['type_id'], ['types.id'], name='topic_types_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
