"""empty message

Revision ID: 72a5fee52c8d
Revises: 6d342dc51870
Create Date: 2025-03-26 13:52:39.901023

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '72a5fee52c8d'
down_revision = '6d342dc51870'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('week_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'week', ['week_id'], ['id'])
        batch_op.drop_column('week')
        batch_op.drop_column('semester')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('semester', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('week', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('week_id')

    # ### end Alembic commands ###
