"""empty message

Revision ID: b82d8a36dd89
Revises: 1932fb4b29c8
Create Date: 2025-03-22 11:26:17.369592

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b82d8a36dd89'
down_revision = '1932fb4b29c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('graduation_year', sa.Integer(), nullable=True))
        batch_op.drop_column('create_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_time', mysql.VARCHAR(length=20), nullable=False))
        batch_op.drop_column('graduation_year')

    # ### end Alembic commands ###
