"""empty message

Revision ID: d155c8eedb21
Revises: f9fc8653098e
Create Date: 2025-03-23 09:38:47.204769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd155c8eedb21'
down_revision = 'f9fc8653098e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('week', schema=None) as batch_op:
        batch_op.add_column(sa.Column('semester_num', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('week', schema=None) as batch_op:
        batch_op.drop_column('semester_num')

    # ### end Alembic commands ###
