"""empty message

Revision ID: da1f96711a21
Revises: d155c8eedb21
Create Date: 2025-03-23 10:42:54.211582

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'da1f96711a21'
down_revision = 'd155c8eedb21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weeks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_num', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.String(length=20), nullable=False),
    sa.Column('end_date', sa.String(length=20), nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.Column('semester_num', sa.Integer(), nullable=False),
    sa.Column('requires_report', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['semester_id'], ['semester.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('week')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('week_id', sa.Integer(), nullable=False))
        batch_op.drop_column('week')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('week', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('week_id')

    op.create_table('week',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('week_num', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('start_date', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('end_date', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('semester_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('requires_report', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('semester_num', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['semester_id'], ['semester.id'], name='week_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('weeks')
    # ### end Alembic commands ###
