"""empty message

Revision ID: ddf7e7a01d7e
Revises: f7f4857016c4
Create Date: 2025-03-09 15:27:04.119339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddf7e7a01d7e'
down_revision = 'f7f4857016c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('semester',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('graduation_year', sa.Integer(), nullable=True),
    sa.Column('first_semester_start_date', sa.String(length=20), nullable=True),
    sa.Column('second_semester_start_date', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('semester')
    # ### end Alembic commands ###
