"""empty message

Revision ID: f9fc8653098e
Revises: 12dde61c3fce
Create Date: 2025-03-23 09:16:50.048926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9fc8653098e'
down_revision = '12dde61c3fce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('week', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requires_report', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('week', schema=None) as batch_op:
        batch_op.drop_column('requires_report')

    # ### end Alembic commands ###
