# Generated by Selenium IDE
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium_test import SeleniumTest


class TestStudentSelectTopics(SeleniumTest):
    """
    This test method tests the student's ability to select topics

    1. The student logs in
    2. The student selects the topics and deselect the topics
    3. The student logs out
    """

    def test_studentSelectTopics(self):
        choose_1 = self.driver.find_element(By.NAME, "choose1")
        self.driver.execute_script("arguments[0].scrollIntoView({block: 'center'});", choose_1)
        time.sleep(1)
        choose_1.click()
        time.sleep(1)
        choose_1.send_keys("PK0014")
        choose_1.send_keys(Keys.ENTER)
        time.sleep(1)

        choose_2 = self.driver.find_element(By.NAME, "choose2")
        self.driver.execute_script("arguments[0].scrollIntoView({block: 'center'});", choose_2)
        time.sleep(1)
        choose_2.click()
        time.sleep(1)
        choose_2.send_keys("PK0012")
        choose_2.send_keys(Keys.ENTER)
        time.sleep(1)

        choose_3 = self.driver.find_element(By.NAME, "choose3")
        self.driver.execute_script("arguments[0].scrollIntoView({block: 'center'});", choose_3)
        time.sleep(1)
        choose_3.click()
        time.sleep(1)
        choose_3.send_keys("PK0002")
        choose_3.send_keys(Keys.ENTER)
        time.sleep(1)

        self.driver.find_element(By.ID, "submit-button").click()
