# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium_test import SeleniumTest


class TestSupervisorcreatetopic(SeleniumTest):
    """
    This test method tests the supervisor's ability to create topics

    1. The supervisor logs in
    2. The supervisor creates a topic
    3. The supervisor logs out
    """
    def test_supervisorcreatetopic(self):
        new_topic_btn = self.driver.find_element(By.LINK_TEXT, "+ New Topic")
        self.driver.execute_script("arguments[0].scrollIntoView({block: 'center'});", new_topic_btn)
        time.sleep(1)
        new_topic_btn.click()
        time.sleep(1)
        self.driver.find_element(By.ID, "topic_name").click()
        self.driver.find_element(By.ID, "topic_name").send_keys("test")
        self.driver.find_element(By.ID, "topic_type").click()
        dropdown = self.driver.find_element(By.ID, "topic_type")
        dropdown.find_element(By.XPATH, "//option[. = 'Machine Learning']").click()
        self.driver.find_element(By.ID, "position").send_keys("1")
        desc = self.driver.find_element(By.ID, "description")
        self.driver.execute_script("arguments[0].scrollIntoView({block: 'center'});", desc)
        time.sleep(1)
        desc.click()
        time.sleep(1)
        desc.send_keys("test")
        self.driver.find_element(By.ID, "skills").send_keys("test")
        refer = self.driver.find_element(By.ID, "reference")
        self.driver.execute_script("arguments[0].scrollIntoView({block: 'center'});", refer)
        time.sleep(1)
        refer.send_keys("test")
        self.driver.find_element(By.CSS_SELECTOR, ".submit-button").click()
