# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium_test import SeleniumTest


class TestManagerSetTypes(SeleniumTest):
    """
    This test method tests the manager's ability to set types

    1. The manager logs in
    2. The manager sets the types
    """

    def test_manager_set_types(self):
        new_note_btn = self.driver.find_element(By.LINK_TEXT, "+ New Type")
        self.driver.execute_script("arguments[0].scrollIntoView({block: 'center'});", new_note_btn)
        time.sleep(1)
        new_note_btn.click()
        time.sleep(1)
        self.driver.find_element(By.ID, "name").click()
        time.sleep(1)
        self.driver.find_element(By.ID, "name").send_keys("4D Game")
        time.sleep(1)
        submit_btn = self.driver.find_element(By.CSS_SELECTOR, ".submit-button")
        self.driver.execute_script("arguments[0].scrollIntoView({block: 'center'});", submit_btn)
        time.sleep(1)
        submit_btn.click()
        time.sleep(1)
        edit_btn = self.driver.find_element(By.CSS_SELECTOR, ".edit-type-btn")
        self.driver.execute_script("arguments[0].scrollIntoView({block: 'center'});", edit_btn)
        time.sleep(1)
        edit_btn.click()
        time.sleep(1)
        self.driver.find_element(By.ID, "name").click()
        time.sleep(1)
        self.driver.find_element(By.ID, "name").click()
        time.sleep(1)
        self.driver.find_element(By.ID, "name").send_keys("3D Game")
        time.sleep(1)
        submit_btn = self.driver.find_element(By.CSS_SELECTOR, ".submit-button")
        self.driver.execute_script("arguments[0].scrollIntoView({block: 'center'});", submit_btn)
        time.sleep(1)
        submit_btn.click()
        time.sleep(1)
        del_btn = self.driver.find_element(By.CSS_SELECTOR, "button.del-btn[data-type-id]")
        self.driver.execute_script("arguments[0].scrollIntoView({block: 'center'});", del_btn)
        time.sleep(1)
        del_btn.click()
        time.sleep(1)
        self.driver.find_element(By.CSS_SELECTOR, ".modal-footer button.btn-danger").click()
        time.sleep(1)
        self.driver.find_element(By.ID, "ok-btn").click()
        time.sleep(1)
