# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium_test import SeleniumTest


class TestStudentCreateCustomTopic(SeleniumTest):
    """
    This test method tests the student's ability to create a custom topic

    1. The student logs in
    2. The student creates a custom topic
    3. The student logs out
    """

    def test_studentCreateCustomTopic(self):
        self.driver.find_element(By.ID, "check_box_note").click()
        self.driver.find_element(By.ID, "custom_topic_name").click()
        self.driver.find_element(By.ID, "custom_topic_name").send_keys("test custom topic")
        supervisor_select = self.driver.find_element(By.ID, "supervisor_id")
        self.driver.execute_script("arguments[0].scrollIntoView({block: 'center'});", supervisor_select)
        time.sleep(1)
        supervisor_select.click()
        time.sleep(1)
        supervisor_select.find_element(By.XPATH, "//option[. = 'clivia li']").click()
        time.sleep(1)
        type_select = self.driver.find_element(By.ID, "type_id")
        self.driver.execute_script("arguments[0].scrollIntoView({block: 'center'});", type_select)
        time.sleep(1)
        type_select.click()
        time.sleep(1)
        type_select.find_element(By.XPATH, "//option[. = 'Machine Learning']").click()
        time.sleep(1)
        desc = self.driver.find_element(By.ID, "field-2")
        self.driver.execute_script("arguments[0].scrollIntoView({block: 'center'});", desc)
        time.sleep(1)
        desc.click()
        desc.send_keys("test")
        save_btn = self.driver.find_element(By.ID, "customFormSubmit")
        self.driver.execute_script("arguments[0].scrollIntoView({block: 'center'});", save_btn)
        time.sleep(1)
        save_btn.click()
        time.sleep(1)
        self.driver.find_element(By.ID, "submit-button").click()  # 'submit application' btn
        time.sleep(1)

