# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.chrome.service import Service

from selenium_test import SeleniumTest


class TestManagerViewTopics(SeleniumTest):
    """
    This test method tests the manager's ability to view topics

    1. The manager logs in
    2. The manager views the detail of a topic
    3. The manager logs out
    """

    def test_managerViewTopics(self):
        self.driver.find_element(By.LINK_TEXT, "Supervisor Topics").click()
        time.sleep(1)
        self.driver.find_element(By.LINK_TEXT, "Detail").click()
        time.sleep(1)
        # todo CRUD of topic
