# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium_test import SeleniumTest


class TestSupervisorViewSelectionResult(SeleniumTest):
    """
    This test method tests the supervisor's ability to view selection results

    1. The supervisor logs in
    2. The supervisor views the selection results
    3. The supervisor logs out
    """

    def test_supervisorViewSelectionResult(self):
        self.driver.get("http://127.0.0.1:8000?test_name=student_selection")
        time.sleep(1)
        self.driver.find_element(By.LINK_TEXT, "My Pickr↗").click()
        time.sleep(1)
        self.driver.find_element(By.ID, "user_name").click()
        time.sleep(1)
        self.driver.find_element(By.ID, "user_name").send_keys("joojo")
        time.sleep(1)
        self.driver.find_element(By.ID, "password").click()
        time.sleep(1)
        self.driver.find_element(By.ID, "password").send_keys("123456")
        time.sleep(1)
        self.driver.find_element(By.CSS_SELECTOR, ".submit-button").click()
        time.sleep(1)
        process_btn = self.driver.find_element(By.LINK_TEXT, "Process")
        self.driver.execute_script("arguments[0].scrollIntoView({block: 'center'});", process_btn)
        time.sleep(1)
        process_btn.click()
        time.sleep(1)
        self.driver.execute_script("window.scrollTo(0,0)")
        self.driver.find_element(By.LINK_TEXT, "My Pickr↗").click()
        time.sleep(1)
        self.driver.find_element(By.XPATH, "//em[contains(.,\'Logout↗\')]").click()
        time.sleep(1)
        self.driver.get("http://127.0.0.1:8000/login")
        time.sleep(1)
        self.driver.find_element(By.ID, "user_name").click()
        time.sleep(1)
        self.driver.find_element(By.ID, "user_name").send_keys("clivia")
        time.sleep(1)
        self.driver.find_element(By.ID, "password").click()
        time.sleep(1)
        self.driver.find_element(By.ID, "password").send_keys("123456")
        time.sleep(1)
        self.driver.find_element(By.CSS_SELECTOR, ".submit-button").click()
        time.sleep(1)
        self.driver.find_element(By.LINK_TEXT, "Applications").click()
        export_btn = self.driver.find_element(By.LINK_TEXT, "→ Export")
        self.driver.execute_script("arguments[0].scrollIntoView({block: 'center'});", export_btn)
        time.sleep(1)
        export_btn.click()
